# permissions for end users to view manors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manor-viewer-role
rules:
- apiGroups:
  - farm.example.com
  resources:
  - manors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - farm.example.com
  resources:
  - manors/status
  verbs:
  - get
