
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - farm.example.com
  resources:
  - manors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - farm.example.com
  resources:
  - manors/finalizers
  verbs:
  - update
- apiGroups:
  - farm.example.com
  resources:
  - manors/status
  verbs:
  - get
  - patch
  - update
